fix failing jetty tests
```
    Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpSessionContext
    	at org.eclipse.jetty.servlet.ServletContextHandler.newSessionHandler(ServletContextHandler.java:339) ~[jetty-servlet-11.0.18.jar:11.0.18]
```